name: "publish"

on:
    push:
        branches:
            - main

jobs:
    publish-tauri:
        permissions:
            contents: write
        strategy:
            fail-fast: false
            matrix:
                include:
                    - platform: "macos-latest"
                      args: "--target aarch64-apple-darwin"
                    - platform: "macos-latest"
                      args: "--target x86_64-apple-darwin"
                    - platform: "ubuntu-22.04"
                      args: ""
                    - platform: "windows-latest"
                      args: ""

        runs-on: ${{ matrix.platform }}
        steps:
            - uses: actions/checkout@v4

            - name: setup node
              uses: actions/setup-node@v4
              with:
                  node-version: lts/*

            - name: setup bun
              uses: oven-sh/setup-bun@v2

            - name: Bump version (patch)
              run: npm version patch

            - name: Commit changes
              run: |
                  git config --local user.email "actions@github.com"
                  git config --local user.name "GitHub Actions"
                  git add package.json package-lock.json
                  git commit -m "chore(release): bump version to $(npm pkg get version)"

            - name: Tag commit
              run: git tag v$(npm pkg get version | tr -d '"')

            - name: Push changes and tags
              uses: ad-m/github-push-action@master
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  tags: true

            - name: install Rust stable
              uses: dtolnay/rust-toolchain@stable
              with:
                  targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

            - name: install dependencies (ubuntu only)
              if: matrix.platform == 'ubuntu-22.04'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

            - name: install frontend dependencies
              run: bun install

            - uses: tauri-apps/tauri-action@v0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tagName: app-v__VERSION__
                  releaseName: "App v__VERSION__"
                  releaseBody: "See the assets to download this version and install."
                  releaseDraft: true
                  prerelease: false
                  args: ${{ matrix.args }}
